[versions]
agp = "8.13.2"
kotlin = "2.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
material = "1.13.0"
activity = "1.12.2"
koin = "4.1.1"
splashScreen = "1.2.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
composeBom = "2025.12.01"
googleFont = "1.10.0"
gson = "2.13.2"
compose = "1.10.0"
room = "2.8.4"

[libraries]
gson = {group = "com.google.code.gson", name = "gson", version.ref = "gson"}

androidx-compose-font = {group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "googleFont"}
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-compose-ui-text = { group = "androidx.compose.ui", name = "ui-text",version.ref = "compose" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version = "1.4.0" }
androidx-compose-material = { group = "androidx.compose.material", name = "material-icons-extended", version = "1.7.8" }
androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version = "2.9.6" }
androidx-compose-koin = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }


androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-splash-screen = {group = "androidx.core", name = "core-splashscreen", version.ref = "splashScreen"}

koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-android-compat = { group = "io.insert-koin", name = "koin-android-compat", version.ref = "koin" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

room = {group = "androidx.room", name = "room-runtime", version.ref= "room"}
room-compiler = {group = "androidx.room", name = "room-compiler", version.ref= "room"}
room-ktx = {group = "androidx.room", name = "room-ktx", version.ref= "room"}

[bundles]
gson = [
    "gson"
]

compose = [
    "androidx-lifecycle-runtime-ktx",
    "androidx-activity-compose",
    "androidx-compose-bom",
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-material3",
    "androidx-compose-material",
    "androidx-compose-ui-text",
    "androidx-compose-navigation",
    "androidx-compose-koin",
    "androidx-compose-font"
]

compose-unit = [
    "androidx-ui-test-manifest",
    "androidx-ui-test-junit4"
]

androidx-ui = [
    "material",
    "androidx-activity",
    "androidx-splash-screen"
]
koin = [
    "koin-core",
    "koin-android",
    "koin-android-compat"
]
junit-test = [
    "androidx-junit",
    "androidx-espresso-core"
]
androidx-basic= [
    "androidx-core-ktx"
]
room = ["room", "room-ktx"]


[plugins]
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version = "2.2.21" }
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dokka = {id = "org.jetbrains.dokka", version = "2.1.0"}